### ISSUE TITLE
 The page does not open in the browser

### ISSUE THREAD

**Issue by DeHb86** [rekryt/iplist#1]
Добрый день!
После установки и запуска контейнера в docker compose, не могу зайти на страницу в браузере, ничего не открывает выдает ошибку - "ERR_CONNECTION_REFUSED".
Устанавливал у себя в домашней лаборатории, после попробовал установить на VPS, но результат такой же.
В браузере естественно разрешен показ незащищенных сайтов.
_________________________________________________________________________

Good afternoon!
After installing and running the container in docker compose, I can't access the page in the browser, it doesn't open anything, it gives an error - "ERR_CONNECTION_REFUSED".
I installed it in my home laboratory, then tried to install it on a VPS, but the result is the same.
The browser is naturally allowed to display unprotected sites.

![image](https://github.com/user-attachments/assets/8f68fbdd-00ef-4eb6-a1f0-bc43f664d803)

**Comment by rekryt** [comment]
По какому адресу открываете?
Должно получиться что-то вроде `http://ip-адрес-vps-сервера:8080/` или `http://ip-адрес-docker-машины:8080/`

**Comment by rekryt** [comment]
Проверьте работоспособность сервиса, например получив список доменов для chatgpt:

```bash
docker compose exec app curl -L "http://localhost:8080/?format=text&data=domains&site=chatgpt.com&wildcard=1"
```
![изображение](https://github.com/user-attachments/assets/446aaef7-4526-4d64-8966-586e55fdc11f)

Посмотрите логи: `docker compose logs -f --tail=50`

**Comment by DeHb86** [comment]
> Проверьте работоспособность сервиса, например получение списка доменов для Chatgpt:


![image](https://github.com/user-attachments/assets/af4350f5-4551-4778-a81b-0a816669c1e6)
По запросу отрабатывает.
В браузере пытаюсь открыть http://ip-адрес-docker-машины:8080/
```
root@iplist:~/iplist#ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0@if78: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether bc:24:11:24:12:f2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.12.249/24 metric 1024 brd 10.10.12.255 scope global dynamic eth0
       valid_lft 535sec preferred_lft 535sec
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:bf:b1:9b:01 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
22: br-b00019e354a1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c8:87:38:4a brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-b00019e354a1
       valid_lft forever preferred_lft forever
28: veth7f326e8@if27: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-b00019e354a1 state UP group default 
    link/ether 22:9d:43:89:37:1d brd ff:ff:ff:ff:ff:ff link-netnsid 1
```

**Comment by rekryt** [comment]
Похоже что должно быть по http://10.10.12.249:8080/
Может быть ufw фаервол блокирует?

Попробуйте на хост-машине `curl -L http://10.10.12.249:8080/`
или с компьютера с которого хост машина доступна:
`curl -L http://10.10.12.249:8080/`

**Comment by DeHb86** [comment]
> Похоже что должно быть по http://10.10.12.249:8080/
> Может быть ufw фаервол блокирует?

Что за магия, только что открыл вашу ссылку и все открылось!

**Comment by rekryt** [comment]
обработка CIDR для ip-адресов вызывает при старте долгую загрузку приложения
скоро поправлю это, сделаю начальную обработку CIDR асинхронной

видимо вы просто не дождались полного старта приложения

**Comment by DeHb86** [comment]
> обработка CIDR для ip-адресов вызывает при старте долгую загрузку приложения скоро поправлю это, сделаю начальную обработку CIDR асинхронной
> 
> видимо вы просто не дождались полного старта приложения

Скорее всего так, ну чтож буду знать :)
Спасибо, за помощь и ответы! И за саму программу!
Завтра уже буду экспериментировать со скриптами на mikrotik.

**Comment by rekryt** [comment]
[Исправлено](https://github.com/rekryt/iplist/commit/6e42686fc79ddf92ebd673ec4e309228a265d7a8)
