### ISSUE TITLE
timeout для записей address-list MikroTik

### ISSUE THREAD

**Issue by tikhomirov-dev** [rekryt/iplist#10]
Здравствуйте :)
Собственно, как гласит заголовок: прошу добавить возможность указать timeout для записей address-list.
Например, в таком виде: `&timeout=1w2d3h4m5s`
Запрашиваем:
`http://iplist.opencck.org/?format=mikrotik&data=cidr4&site=discord.com&timeout=1w2d3h4m5s`
На выходе получаем:
`/ip firewall address-list
add list=discord_cidr4 address=104.16.0.0/12 comment=discord.com timeout=1w2d3h4m5s`
Какой от этого профит? Записи хранятся в оперативке, а не записываются на диск

**Comment by rekryt** [comment]
Хорошо, готово.

https://github.com/rekryt/iplist/commit/800a2eb06e9908f30ceff9ce0ba52b1eeab01a8c

https://iplist.opencck.org/?format=mikrotik&data=cidr4&site=discord.com&append=timeout%3D1w2d3h4m5s
