### ISSUE TITLE
TMDB

### ISSUE THREAD

**Issue by urtaevS** [rekryt/iplist#20]
Добавьте пожалуйста адреса для:

- https://www.themoviedb.org/
- http://image.tmdb.org/

**Comment by rekryt** [comment]
![image](https://github.com/user-attachments/assets/37c51fb8-7559-40f6-a656-ccc18a7ece02)

но они ведь не заблокированы

**Comment by urtaevS** [comment]
Странно. Что-то у меня сбоит значит.
Прошу прощенияю

**Comment by rekryt** [comment]
![image](https://github.com/user-attachments/assets/f6ee1080-3921-4e97-a0a5-771538da453c)
https://qna.habr.com/q/1145050

нет, вы правы, в России они не работают

**Comment by rekryt** [comment]
Готово: https://github.com/rekryt/iplist/commit/e15cfaa32a837162ea05d40cb0a7758b8b7b37f5
https://iplist.opencck.org/?format=text&data=cidr4&site=themoviedb.org

**Comment by urtaevS** [comment]
Спасибо!
Просто лучший!
