### ISSUE TITLE
Ошибка импорта на Mikrotik

### ISSUE THREAD

**Issue by log-box** [rekryt/iplist#8]
При выолнении скрипта на Mikrotik он падает с ошибкой на строчке
...
/import file-name=iplist_v4_cidr.rsc
Это происходит потому, что в файле iplist_v4_cidr.rsc есть такая строчка:
add list=youtube_cidr4 address= comment=youtube.com

Она находится в области:
...
/ip firewall address-list remove [find list="youtube_cidr4"];
:delay 5s

/ip firewall address-list
add list=youtube_cidr4 **address=** comment=youtube.com
add list=youtube_cidr4 address=103.200.28.0/22 comment=youtube.com
...

**Comment by rekryt** [comment]
![изображение](https://github.com/user-attachments/assets/7f321a2f-338e-4f7e-9b8d-9d24b532fc73)

Расскажите как настраиваете?
В планировщике скрипт должен быть примерно такой:
```
/tool fetch url="https://iplist.opencck.org/?format=mikrotik&data=cidr4" mode=https dst-path=iplist_v4_cidr.rsc
:delay 5s
:log info "Downloaded iplist_v4_cidr.rsc succesfully";

/import file-name=iplist_v4_cidr.rsc
:delay 10s
:log info "New iplist_v4_cidr added successfully";
```

Если нужно только для youtube, тогда такой:
```
/tool fetch url="https://iplist.opencck.org/?format=mikrotik&data=cidr4&site=youtube.com" mode=https dst-path=iplist_v4_cidr.rsc
:delay 5s
:log info "Downloaded iplist_v4_cidr.rsc succesfully";

/import file-name=iplist_v4_cidr.rsc
:delay 10s
:log info "New iplist_v4_cidr added successfully";
```

Как у вас получился пустой адрес?
```
add list=youtube_cidr4 address= comment=youtube.com
```

**Comment by log-box** [comment]
/tool fetch url="http://192.168.1.2:1999/?format=mikrotik&data=cidr4" mode=http dst-path=iplist_v4_cidr.rsc
:delay 5s
:log info "Downloaded iplist_v4_cidr.rsc succesfully";

/import file-name=iplist_v4_cidr.rsc
:delay 10s
:log info "iplist_v4_cidr.rsc added successfully";

Но это не в Mikrotik дело, такой же файл формируется если через браузер открыть http://192.168.1.2:1999/?format=mikrotik&data=cidr4

**Comment by log-box** [comment]
![изображение](https://github.com/user-attachments/assets/b6b3be89-fcab-481f-a46b-51b53413d303)

**Comment by rekryt** [comment]
Понял. Можете дать свой youtube.com.json конфиг.

**Comment by log-box** [comment]
![изображение](https://github.com/user-attachments/assets/e94a68a4-e23b-4194-b7d4-197cbb3db069)

**Comment by log-box** [comment]
[youtube.com.json](https://github.com/user-attachments/files/17530799/youtube.com.json)

Вот конфиг. Но я не менял его вроде ...

**Comment by rekryt** [comment]
Да, проблему вижу. Разбираюсь.

**Comment by rekryt** [comment]
Спасибо, исправил.

https://github.com/rekryt/iplist/commit/c2814aab54ea33f16400b873083f3709bbf214d8

**Comment by log-box** [comment]
Вам спасибо! 
Сервис огонь! Добавил его в systemctl на правах обязательного компонента!
