### ISSUE TITLE
Конфиги для сервисов JetBrains

### ISSUE THREAD

**Issue by Fenoman** [rekryt/iplist#9]
Доброго времени суток! А нельзя ли добавить конфиги для jetbrains и для jetbrains-ai? 
Вот тут можно взять списки доменов:
https://github.com/v2fly/domain-list-community/blob/master/data/jetbrains
https://github.com/v2fly/domain-list-community/blob/master/data/jetbrains-ai

**Comment by rekryt** [comment]
Есть некоторые конфиги для jetbrains вот тут:
https://beta.iplist.opencck.org/

Хорошо, изучу представленные списки, проверю по самим сайтам нет ли ещё каких-либол доменов, добавлю.

**Comment by rekryt** [comment]
Добавлено.

https://github.com/rekryt/iplist/commit/3e9c9db62d40b872de7fe0f67de288e650b2ca2a
